version: '3.4'
services: 
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - /u/91/rajr1/unix/Documents/rohitthesis/code/Monitoring_and_tests/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
